version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  back-end:
    build: .
    ports:
      - 3000:3000
    
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongodb:27017/patient_details