version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongodb:27017/Users